# Maps report reasons to removal reason titles and descriptions
removal_reasons = {
'Be Civil, No Witch Hunting, Trolling, or Violating Reddiquette': {'title': 'Be Civil, No Witch Hunting, Trolling, or Violating Reddiquette', 'message': 'Be civil and respectful of others and follow Reddiquette. No witch hunting or calling out of specific people is allowed. Any post that does so will be removed. Trolling or anything that violates Reddiquette will be removed. This includes putting anything like "repost", "Posting again, forgot flair", etc. in your title.  These posts will also be removed and can be reposted without those in the title.'},
'Haul posts must be properly formatted.': {'title': 'Haul', 'message': 'This post was removed for one of two reasons:\n\n1) You must always include either the State, Country (If outside the US) for in person hauls, or online store name if ordered online, in the title of all haul posts.\n\n2) Hauls must not contain duplicate items.\n\nIf you get your post removed for one of these reasons, please **do not** just repost with the exact same title but using the collection flair. This is still a haul, no matter what flair you place on it. Please follow the haul rules.\n\n***This comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.\n\n***'},
'No Buying, Selling, or Trading': {'title': 'No Buying, Selling, or Trading', 'message': 'Posting a B/S/T thread on r/funkopop will result in a one day ban. Please use r/funkoswap for B/S/T instead.'},
'No promotion of bots/flipping': {'title': 'No promotion of bots/flipping', 'message': 'No discussing/bragging about flipping or using bots to order rare or large quantities of items. We are first and foremost a community for and of collectors so let\'s work to keep it that way.'},
'No posts that belong in megathreads or are answered in the FAQ': {'title': 'Megathread', 'message': 'This post was removed for one of three reasons:\n\n1) This post belongs in a special mega thread, stickied to the top of the sub under "Hot"\n\n2) This post belongs in one of the weekly or monthly threads, posted and stickied automatically. Please view the side bar or wiki for more information on these threads.\n\n3) This post is a question already covered in [the FAQ of the sub](https://www.reddit.com/r/funkopop/wiki/faq_funko).\n\n***\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'},
'No Self Promotion out of Mega Thread/preorder posts': {'title': 'Self Promotion', 'message': 'This post has been removed because we do not allow self promotion outside of the weekly Community Promotion Thursday sticky post. Self promotion includes:\n\n1) Images or original content with a water mark on it, unless the water mark exactly matches your reddit user name and does not include any @ characters\n\n2) Links to stores that you own or operate\n\n3) Links containing affiliate ids\n\n4) Links to eBay or other sites where you are selling anything\n\n***\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'},
'No Low Quality Leaks': {'title': 'Leak', 'message': 'There are two reasons for a leak to be remove:\n\n1) This post has been removed as it does not meet our standards for a "leak." We require at least some shred of evidence for a leak to be considered legit. Just having an image of names of characters on an image does not qualify as a proper leak. In fact, we have seen people post fake leaks before. And occasionally, these leaks never even come through. It is for these reasons that we require more proof before allowing a leak.\n\n2) Leaks which are covered in Water Marks that obscure the subject of the image will be removed.\n\nYour post violates one of those two conditions and has been removed. Thanks for your understanding.\n\n***\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'},
'Tracking Post must include location or online link': {'title': 'Tracking', 'message': 'This post was removed because tracking Posts require Location(State & City). No Reverse Tracking Posts.\n***\n\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'},
'No Duplicate Posts': {'title': 'Duplicate Post', 'message': 'This post was removed because it is a duplicate post.\n\n***\n\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'},
'Giveways must be approved by moderators': {'title': 'Giveaway', 'message': 'Giveways must be approved by moderators. Please reply to this message if you are still interested in hosting your giveaway.'},
'Spoilers': {'title': 'Spoilers', 'message': 'This submission has been removed because it contains spoilers. Spoilers can be posted after:\n\n* One Week for TELEVISION SHOWS\n\n* One Month for MOVIES\n\nBans will be given based on the severity of the spoiler.\n***\n\nThis comment was left automatically and as a courtesy to you. If you have any questions, please reply to this message.'}
}
